// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NotificationModule.Shared.Persistence;

#nullable disable

namespace NotificationModule.Shared.Migrations;

[DbContext(typeof(NotificationDbContext))]
[Migration("20250518110000_AddOrganizationsAndAppointments")]
partial class AddOrganizationsAndAppointments
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        NotificationDbContextModelSnapshot.BuildCurrentModel(modelBuilder);
    }
}
