// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NotificationModule.Shared.Persistence;

#nullable disable

namespace NotificationModule.Shared.Migrations;

[DbContext(typeof(NotificationDbContext))]
[Migration("20250513120000_InitialSecrets")]
partial class InitialSecrets
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("NotificationModule.Shared.Persistence.ProviderSecretRecord", b =>
        {
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<byte[]>("EncryptedPayload")
                .IsRequired()
                .HasColumnType("bytea");

            b.Property<byte[]>("Nonce")
                .IsRequired()
                .HasColumnType("bytea");

            b.Property<string>("Provider")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Provider");

            b.ToTable("provider_secrets");
        });
    }
}
