// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NotificationModule.Shared.Persistence;

#nullable disable

namespace NotificationModule.Shared.Migrations;

[DbContext(typeof(NotificationDbContext))]
[Migration("20250518113000_AddNotificationDeliveries")]
partial class AddNotificationDeliveries
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        NotificationDbContextModelSnapshot.BuildCurrentModel(modelBuilder);
    }
}
