// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using NotificationModule.Shared.Persistence;

#nullable disable

namespace NotificationModule.Shared.Migrations;

[DbContext(typeof(NotificationDbContext))]
partial class NotificationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        BuildCurrentModel(modelBuilder);
    }

    internal static void BuildCurrentModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("NotificationModule.Shared.Persistence.AppointmentRecord", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("AppointmentUuid")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Instructions")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<string>("Location")
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<Guid>("OrganizationId")
                .HasColumnType("uuid");

            b.Property<string>("PatientEmail")
                .HasMaxLength(320)
                .HasColumnType("character varying(320)");

            b.Property<string>("PatientName")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("PatientPhone")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<string>("PatientUuid")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<DateTimeOffset?>("PiiPurgedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("RawSourcePayload")
                .HasColumnType("jsonb");

            b.Property<string>("SourceSystem")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTimeOffset>("StartDateTime")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("OrganizationId", "AppointmentUuid")
                .IsUnique();

            b.HasIndex("OrganizationId", "StartDateTime");

            b.HasIndex("PiiPurgedAt", "CreatedAt");

            b.ToTable("appointments");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.BillingDeliveryEventRecord", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<Guid>("OrganizationId")
                .HasColumnType("uuid");

            b.Property<string>("Provider")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<string>("ReminderType")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<DateTimeOffset>("OccurredAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("CorrelationId")
                .HasColumnType("uuid");

            b.Property<string>("ProviderMessageId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.HasKey("Id");

            b.HasIndex("OccurredAt");

            b.HasIndex("OrganizationId", "OccurredAt");

            b.ToTable("billing_delivery_events");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.OrganizationRecord", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("FallbackProviders")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<bool>("IsEnabled")
                .HasColumnType("boolean");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("OpenMrsBaseUrl")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("PreferredProvider")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<string>("TimeZone")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("Key")
                .IsUnique();

            b.ToTable("organizations");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.OrganizationApiKeyRecord", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<bool>("IsEnabled")
                .HasColumnType("boolean");

            b.Property<byte[]>("KeyHash")
                .IsRequired()
                .HasColumnType("bytea");

            b.Property<Guid>("OrganizationId")
                .HasColumnType("uuid");

            b.Property<byte[]>("Salt")
                .IsRequired()
                .HasColumnType("bytea");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("OrganizationId");

            b.ToTable("organization_api_keys");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.NotificationDeliveryRecord", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<Guid>("AppointmentId")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("ErrorMessage")
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)");

            b.Property<DateTimeOffset?>("FailedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("OrganizationId")
                .HasColumnType("uuid");

            b.Property<string>("Provider")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<string>("ProviderMessageId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<Guid>("ScheduledNotificationId")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset?>("SentAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("AppointmentId");

            b.HasIndex("OrganizationId", "Status", "UpdatedAt");

            b.HasIndex("ScheduledNotificationId", "Provider")
                .IsUnique();

            b.ToTable("notification_deliveries");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.ProviderSecretRecord", b =>
        {
            b.Property<Guid>("OrganizationId")
                .HasColumnType("uuid");

            b.Property<string>("Provider")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<byte[]>("EncryptedPayload")
                .IsRequired()
                .HasColumnType("bytea");

            b.Property<byte[]>("Nonce")
                .IsRequired()
                .HasColumnType("bytea");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("OrganizationId", "Provider");

            b.ToTable("provider_secrets");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.ScheduledNotificationRecord", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<Guid>("AppointmentId")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("OrganizationId")
                .HasColumnType("uuid");

            b.Property<string>("ReminderType")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<DateTimeOffset>("ScheduledSendAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("AppointmentId");

            b.HasIndex("OrganizationId", "Status", "ScheduledSendAt");

            b.ToTable("scheduled_notifications");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.AppointmentRecord", b =>
        {
            b.HasOne("NotificationModule.Shared.Persistence.OrganizationRecord", "Organization")
                .WithMany("Appointments")
                .HasForeignKey("OrganizationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Organization");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.OrganizationApiKeyRecord", b =>
        {
            b.HasOne("NotificationModule.Shared.Persistence.OrganizationRecord", "Organization")
                .WithMany("ApiKeys")
                .HasForeignKey("OrganizationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Organization");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.ProviderSecretRecord", b =>
        {
            b.HasOne("NotificationModule.Shared.Persistence.OrganizationRecord", "Organization")
                .WithMany("ProviderSecrets")
                .HasForeignKey("OrganizationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Organization");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.NotificationDeliveryRecord", b =>
        {
            b.HasOne("NotificationModule.Shared.Persistence.AppointmentRecord", "Appointment")
                .WithMany("Deliveries")
                .HasForeignKey("AppointmentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("NotificationModule.Shared.Persistence.OrganizationRecord", "Organization")
                .WithMany()
                .HasForeignKey("OrganizationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("NotificationModule.Shared.Persistence.ScheduledNotificationRecord", "ScheduledNotification")
                .WithMany("Deliveries")
                .HasForeignKey("ScheduledNotificationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Appointment");

            b.Navigation("Organization");

            b.Navigation("ScheduledNotification");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.ScheduledNotificationRecord", b =>
        {
            b.HasOne("NotificationModule.Shared.Persistence.AppointmentRecord", "Appointment")
                .WithMany("ScheduledNotifications")
                .HasForeignKey("AppointmentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("NotificationModule.Shared.Persistence.OrganizationRecord", "Organization")
                .WithMany()
                .HasForeignKey("OrganizationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Appointment");

            b.Navigation("Organization");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.AppointmentRecord", b =>
        {
            b.Navigation("Deliveries");

            b.Navigation("ScheduledNotifications");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.OrganizationRecord", b =>
        {
            b.Navigation("ApiKeys");

            b.Navigation("Appointments");

            b.Navigation("ProviderSecrets");
        });

        modelBuilder.Entity("NotificationModule.Shared.Persistence.ScheduledNotificationRecord", b =>
        {
            b.Navigation("Deliveries");
        });
    }
}
