apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    uid: bfmgfsmp6bpj4a
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    user: notification
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: notification
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
