FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "src/NotificationModule.Consumer/NotificationModule.Consumer.csproj"
RUN dotnet publish "src/NotificationModule.Consumer/NotificationModule.Consumer.csproj" \
    -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "NotificationModule.Consumer.dll"]

