// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NotificationModule.Consumer.Secrets;

#nullable disable

namespace NotificationModule.Consumer.Migrations;

[DbContext(typeof(SecretsDbContext))]
[Migration("20250513120000_InitialSecrets")]
partial class InitialSecrets
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("NotificationModule.Consumer.Secrets.ProviderSecretRecord", b =>
        {
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<byte[]>("EncryptedPayload")
                .IsRequired()
                .HasColumnType("bytea");

            b.Property<byte[]>("Nonce")
                .IsRequired()
                .HasColumnType("bytea");

            b.Property<string>("Provider")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Provider");

            b.ToTable("provider_secrets", (string?)null);
        });
#pragma warning restore 612, 618
    }
}
